---
# !!IMPORTANT!!
# All false boolean values should be quoted due to https://github.com/helm/helm/issues/3308
# Because of YAML merging, all true boolean values should be quoted as well
environments:
  default:
  __base:
  dev:
  int:
---

bases:
  - "helmfile/bases/helmDefaults.yaml"

helmfiles:
  - "helmfile/releases/helmfile.yaml"

missingFileHandler: Error